# docker-compose.yml - e2e/dev stack for NotePulse

x-server-core: &server-core
  build:
    context: .
    dockerfile: Dockerfile
  image: notepulse-server:latest
  environment:
    LOG_LEVEL: ${LOG_LEVEL:-debug}
    MONGO_URI: mongodb://root:example@mongo:27017/
    MONGO_DB_NAME: notepulse
    JWT_SECRET: ${JWT_SECRET:-change-me}
    APP_PORT: 8080
  depends_on:
    - mongo
  healthcheck:
    test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1/healthz || exit 1"]
    interval: 30s
    timeout: 5s
    start_period: 5s
    retries: 3
  restart: unless-stopped

services:
  mongo:
    image: mongo:8.0
    container_name: notepulse-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notepulse
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 127.0.0.1:27017:27017

  server:
    <<: *server-core
    container_name: notepulse-server
    ports: []        # no external port publish during CI/e2e

  # --- "dev" profile: expose ports for local development -----------------
  mongo-dev:
    extends:
      service: mongo
    profiles: ["dev"]
    container_name: notepulse-mongo-dev
    ports:
      - 27017:27017

  server-dev:
    extends:
      service: server
    profiles: ["dev"]
    container_name: notepulse-server-dev
    environment:
      LOG_LEVEL: debug
      MONGO_URI: mongodb://root:example@mongo:27017/
      MONGO_DB_NAME: notepulse
      JWT_SECRET: ${JWT_SECRET:-change-me}
      APP_PORT: 8080
    ports:
      - 8080:8080

volumes:
  mongo-data: {}
