# docker-compose.rs.yml  (override only)
services:
  mongo:
    image: mongo:8.0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

    # remove the auth-enabling vars coming from the base file
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:

    healthcheck:
      test: |
        CMD-SHELL
        mongosh --quiet --eval '
          const hello = db.hello();
          if (hello.isWritablePrimary) quit(0);
          quit(1);
        '
      interval: 5s
      timeout: 5s
      retries: 20

  mongo-rs-init:
    image: mongo:8.0
    depends_on: [mongo]
    entrypoint:
      - bash
      - -c
      - |
        for i in {1..20}; do
          if mongosh "mongodb://mongo:27017" --quiet --eval "quit()"; then
            break; fi;
          sleep 2;
        done &&
        mongosh "mongodb://mongo:27017" --quiet --eval 'rs.initiate({_id:"rs0", members:[{_id:0, host:"mongo:27017"}]});' || true
    restart: "no"


  server:
    environment:
      MONGO_URI: mongodb://mongo:27017/?replicaSet=rs0
    depends_on:
      mongo-rs-init:
        condition: service_completed_successfully
