x-server-core: &server-core
  build:
    context: .
    dockerfile: Dockerfile
  image: notepulse-server:latest
  env_file:
    - .env.example
  depends_on:
    - mongo
  healthcheck:
    test: ["CMD", "/ping"]
    interval: 30s
    timeout: 5s
    retries: 3
    start_period: 5s
  restart: on-failure:3

services:
  mongo:
    image: mongo:8.0
    container_name: notepulse-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notepulse
    volumes:
      - mongo-data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    <<: *server-core
    container_name: notepulse-server
    ports:
      - 8080:8080

volumes:
  mongo-data: {}
